### ISSUE TITLE
Parameter name `sitename` for Open Graph is wrong

### ISSUE THREAD

**Issue by codiflow** [HashandSalt/kirby3-seo#3]
First I wanna thank you for this great plugin. It saved me a lot of time.

During my customization I found a small issue:

In the file `snippets/meta.php` the parameter is named `og:sitename`. But the specification at https://ogp.me says it should be `og:site_name`.

**Comment by codiflow** [comment]
I would also consider adding `og:locale` as it could be a multi language site and if its not specified the standard says the language code is `en_us`.

**Comment by HashandSalt** [comment]
Thanks for the suggestions. I have fixed `og:site_name` and added the locale option. You can add more if you need by adding them to your controllers, and adding an appropriate tag in the meta snippet. If its something useful to many people,  i will consider adding more to the default setup.
