### ISSUE TITLE
[K4] 4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [HashandSalt/kirby3-seo#6]
Minor UI issue on sidebar width

![screen-capture-1755-Site - Mægazine-plugins test](https://github.com/HashandSalt/kirby3-seo/assets/3393422/99c90daf-c446-490d-bae8-e236ccf872d5)

Kirby 4.0.0-rc.4
PHP 8.1.23

**Comment by HashandSalt** [comment]
Thanks @ahmet .. can't see this myself..

![image](https://github.com/HashandSalt/kirby3-seo/assets/28439755/2a594c2c-47ec-4034-8c54-87312b911844)

Kirby 4.0
PHP 8.2.11

**Comment by afbora** [comment]
OK let me test again.

**Comment by afbora** [comment]
Still same for me. Try wide screen please (1920x1080px for me)

**Comment by HashandSalt** [comment]
@afbora Managed to replicate this. Its fixed in newly released K4 version of the plugin https://github.com/HashandSalt/kirby4-seo
